version: "2"
## Create MacVLAN Network.  This allows each host to have a unique IP address assigned
## from the DHCP scope.
networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip-range: 192.168.1.192/28
## Define Pi-Hole Service and Container Detail
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      pihole_network:
        ipv4_address: 192.168.1.199
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 192.168.1.199
      WEBPASSWORD: ""  ##Set Admin Portal Password
      VIRTUAL_HOST: pihole
    restart: unless-stopped
